/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lojainformatica.view;

import com.mycompany.lojainformatica.dao.ComputadoresDAO;
import javax.swing.JOptionPane;
import com.mycompany.lojainformatica.model.Computador;

/**
 *
 * @author alexs Crie uma interface (JFrame) para gravar estas informações no
 * banco de dados usando JDBC
 */
public class TelaComputadores extends javax.swing.JFrame {

    /**
     * vindo da tela de consulta para a de cadastro para alterar
     */
    Computador objComputador;

    /**
     * Creates new form Computadores
     */
    public TelaComputadores() {
        initComponents();
    }

    public TelaComputadores(Computador obj) {
        initComponents();

        //Pegar os dados do obj e passar para o formulário
        cboProcessador.setSelectedItem(String.valueOf(obj.getPrecessador()));
        cboHD.setSelectedItem(String.valueOf(obj.getHD()));

        this.objComputador = obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboHD = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cboProcessador = new javax.swing.JComboBox<>();
        label1 = new java.awt.Label();
        btnConsultarTelaCadastrar = new javax.swing.JButton();
        lblMarca = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cboHD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um tipo de hd...", "HDD 512 GB", "HDD 1TB", "SSD 256GB", "SSD 512GB", "SSD 1TB" }));
        cboHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboHDActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel2.setText("Marca :");

        cboProcessador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um tipo de Processador...", "i5 10400F", "Ryzen 5 3600", "Ryzen 3 3200G", "Ryzen 3 3200X", "Ryzen 3 3200A", " ", " " }));
        cboProcessador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboProcessadorActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24)); // NOI18N
        label1.setText("Montando um computador ");

        btnConsultarTelaCadastrar.setText("Consultar ");
        btnConsultarTelaCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarTelaCadastrarActionPerformed(evt);
            }
        });

        lblMarca.setText("AlexsandroLopes\n");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboHD, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboProcessador, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 147, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsultarTelaCadastrar)
                        .addGap(193, 193, 193))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cboProcessador, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarTelaCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cboProcessadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboProcessadorActionPerformed

    }//GEN-LAST:event_cboProcessadorActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        /* validando se nenhuma opçao foi selecionada  */
        if (objComputador == null) {
            if (cboProcessador.getSelectedIndex() == 0 && cboHD.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(rootPane, " Selecione as opçoes de hd e Processador !");
            } else if (cboProcessador.getSelectedIndex() == 0) {/* se apenas o hd foi selecionado*/
                JOptionPane.showMessageDialog(rootPane, " Selecione um processador !");
            } else if (cboHD.getSelectedIndex() == 0) {
                /* se apenas o  processador foi selecionado */
                JOptionPane.showMessageDialog(rootPane, " Selecione um HD !");
            } else {
                String processador = (cboProcessador.getSelectedItem().toString());
                String hd = (cboHD.getSelectedItem().toString());

                Computador objTelaCadastro = new Computador();
                objTelaCadastro.setHD(hd);
                objTelaCadastro.setPrecessador(processador);

                boolean retorno = ComputadoresDAO.salvar(objTelaCadastro);

                if (retorno) {
                    JOptionPane.showMessageDialog(rootPane, "cadastrado !");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Não foi possivel cadastrar!!");
                }
            }

        } else if (objComputador != null && objComputador.getNumeroDoComputador() > 0) {

            if (cboProcessador.getSelectedIndex() == 0 && cboHD.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(rootPane, " Selecione as opçoes de hd e Processador !");
            } else if (cboProcessador.getSelectedIndex() == 0) {/* se apenas o hd foi selecionado*/
                JOptionPane.showMessageDialog(rootPane, " Selecione um processador !");
            } else if (cboHD.getSelectedIndex() == 0) {
                /* se apenas o  processador foi selecionado */
                JOptionPane.showMessageDialog(rootPane, " Selecione um HD !");
            } else {

                String processador = (cboProcessador.getSelectedItem().toString());
                String hd = (cboHD.getSelectedItem().toString());

                objComputador.setPrecessador(processador);
                objComputador.setHD(hd);

                boolean retorno = ComputadoresDAO.alterar(objComputador);
                if (retorno) {
                    JOptionPane.showMessageDialog(rootPane, "Sucesso na alteração!");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Falha na alteração!");
                }
            }

        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void cboHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboHDActionPerformed

    }//GEN-LAST:event_cboHDActionPerformed

    private void btnConsultarTelaCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarTelaCadastrarActionPerformed
        TelaConsulta chamarTelaConsulta = new TelaConsulta();
        chamarTelaConsulta.setVisible(true);


    }//GEN-LAST:event_btnConsultarTelaCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaComputadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaComputadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaComputadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaComputadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaComputadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarTelaCadastrar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cboHD;
    private javax.swing.JComboBox<String> cboProcessador;
    private javax.swing.JLabel jLabel2;
    private java.awt.Label label1;
    private java.awt.Label lblMarca;
    // End of variables declaration//GEN-END:variables
}
